"""Tests for issue #1960: Add GET /api/dev-report endpoint to dashboard (runs against UAT)"""
import os
import json
import pytest
import httpx


BASE_URL = os.environ.get("UAT_BASE_URL") or "http://localhost:" + os.environ.get("UAT_PORT", "")
if not BASE_URL.startswith("http"):
    raise RuntimeError(
        "UAT_BASE_URL / UAT_PORT not set. Run the tester skill's Step 0 to resolve UAT before pytest."
    )


@pytest.fixture
def client():
    with httpx.Client(base_url=BASE_URL, timeout=10.0) as c:
        yield c


# --- Acceptance Criteria ---

def test_dev_report_api__returns_stored_artifact_for_today(client):
    # AC: GET /api/dev-report returns the stored `dev_report` artifact payload for today (Bangkok timezone) by default
    # First, ensure an artifact exists for today by calling with ?force=1
    r_force = client.get("/api/dev-report?force=1")
    assert r_force.status_code == 200
    stored_payload = r_force.json()
    assert isinstance(stored_payload, dict)
    assert "for_date" in stored_payload
    assert "projects" in stored_payload or "completed" in stored_payload

    # Now retrieve without force flag and verify it's the same stored payload
    r = client.get("/api/dev-report")
    assert r.status_code == 200
    retrieved_payload = r.json()
    assert retrieved_payload == stored_payload


def test_dev_report_api__returns_artifact_for_specified_date(client):
    # AC: GET /api/dev-report?date=YYYY-MM-DD returns the artifact for the specified date
    # First ensure we have an artifact for a specific past date by forcing generation
    test_date = "2026-07-10"
    r_force = client.get(f"/api/dev-report?date={test_date}&force=1")
    assert r_force.status_code == 200
    stored_payload = r_force.json()
    assert "for_date" in stored_payload

    # Retrieve the same date without force
    r = client.get(f"/api/dev-report?date={test_date}")
    assert r.status_code == 200
    retrieved_payload = r.json()
    assert retrieved_payload == stored_payload
    assert retrieved_payload["for_date"] == test_date


def test_dev_report_api__404_when_no_artifact_exists_and_no_force(client):
    # AC: When no artifact exists for the date and `force` is not set, the endpoint returns HTTP 404 with body `{\"error\": \"<descriptive message>\"}`
    # Use a date that won't be generated by other tests. We pick a date in the past that's unlikely to be queried.
    past_date = "2020-01-01"
    r = client.get(f"/api/dev-report?date={past_date}")
    # Note: this test assumes the artifact was not pre-generated; if it was, the test will fail
    # and that's OK because it means the AC is not properly implemented
    assert r.status_code == 404
    error_body = r.json()
    assert "error" in error_body
    assert past_date in error_body["error"]
    assert "No dev report artifact found" in error_body["error"]


def test_dev_report_api__force_regenerates_and_stores(client):
    # AC: GET /api/dev-report?force=1 regenerates the artifact inline (invoking the shared assembly function) and stores the result before returning it
    # Force generation for a specific date
    test_date = "2026-07-11"
    r_force = client.get(f"/api/dev-report?date={test_date}&force=1")
    assert r_force.status_code == 200
    force_payload = r_force.json()
    assert isinstance(force_payload, dict)
    assert "for_date" in force_payload
    assert force_payload["for_date"] == test_date

    # Verify it was stored by retrieving without force
    r_stored = client.get(f"/api/dev-report?date={test_date}")
    assert r_stored.status_code == 200
    stored_payload = r_stored.json()
    # The payloads should match (same data, though timestamps may differ)
    assert stored_payload["for_date"] == force_payload["for_date"]


def test_dev_report_api__force_and_date_together(client):
    # AC: GET /api/dev-report?date=YYYY-MM-DD&force=1 regenerates and stores the artifact for the given date
    test_date = "2026-07-12"
    r = client.get(f"/api/dev-report?date={test_date}&force=1")
    assert r.status_code == 200
    payload = r.json()
    assert payload["for_date"] == test_date

    # Retrieve again without force to confirm it was stored
    r2 = client.get(f"/api/dev-report?date={test_date}")
    assert r2.status_code == 200
    assert r2.json()["for_date"] == test_date
