#!/usr/bin/env bash
# install_shell_shortcuts.sh — Append Commander shell functions to ~/.commander.zsh.
#
# Run once to install. Add the following line to ~/.zshrc if not already present:
#   source ~/.commander.zsh
#
# Usage:
#   bash ~/commander/dashboard/scripts/install_shell_shortcuts.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DASHBOARD_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
COMMANDER_ROOT="$(cd "$DASHBOARD_DIR/.." && pwd)"

TARGET="$HOME/.commander.zsh"
CMDR_SCRIPTS_EXPANDED="$SCRIPT_DIR"

BLOCK=$(cat <<ZSHBLOCK
# ── Commander shell shortcuts ──────────────────────────────────────────────────
# Generated by dashboard/scripts/install_shell_shortcuts.sh
# Add \`source ~/.commander.zsh\` to your ~/.zshrc to enable these functions.
#
# NOTE: \`cmdr-status\` is named with the \`cmdr-\` prefix to avoid shadowing the
#       macOS /usr/bin/stat command that some tools invoke as \`status\`.

CMDR_SCRIPTS="$CMDR_SCRIPTS_EXPANDED"

start-prd()    { bash "\$CMDR_SCRIPTS/start_prd.sh" "\$@"; }
start-uat()    { bash "\$CMDR_SCRIPTS/start_uat.sh" "\$@"; }
stop-prd()     { bash "\$CMDR_SCRIPTS/stop_all.sh" prd "\$@"; }
stop-uat()     { bash "\$CMDR_SCRIPTS/stop_all.sh" uat "\$@"; }
stop-all()     { bash "\$CMDR_SCRIPTS/stop_all.sh" "\$@"; }
cmdr-status()  { bash "\$CMDR_SCRIPTS/status.sh" "\$@"; }
restart-prd()  { stop-prd && sleep 1 && start-prd; }
restart-uat()  { stop-uat && sleep 1 && start-uat; }
# ─────────────────────────────────────────────────────────────────────────────
ZSHBLOCK
)

if [ -f "$TARGET" ] && grep -q "Commander shell shortcuts" "$TARGET"; then
    echo "Commander shell shortcuts already present in $TARGET — skipping."
else
    echo "$BLOCK" >> "$TARGET"
    echo "Appended Commander shell shortcuts to $TARGET."
fi

# Remind the user to source the file in .zshrc
if ! grep -q "source.*\.commander\.zsh" "$HOME/.zshrc" 2>/dev/null; then
    echo ""
    echo "ACTION REQUIRED: add the following line to your ~/.zshrc:"
    echo "  source ~/.commander.zsh"
fi
