#!/usr/bin/env python3
"""Provision session-wide Claude Code hooks so Commander telemetry fires from any repo.

By default Claude Code only loads hooks from the project's .claude/settings.json,
so hooks never fire when working in a managed project's worktree (e.g. viral-radar).
This script adds hooks to ~/.claude/settings.json so they fire regardless of which
repo is active, feeding the Running view from hand-driven coder/tester sessions.

Usage:
    python3 scripts/provision_global_hooks.py [--commander-dir <path>] [--dry-run]

Options:
    --commander-dir <path>  Path to the commander prd clone (default: ~/dev/commander/prd)
    --dry-run               Print what would change without writing anything
"""
import argparse
import json
import os
import sys
from pathlib import Path


HOOK_NAMES = {
    "run_tool_used.sh": "run_tool_used.sh",
    "run_post_tool_used.sh": "run_post_tool_used.sh",
    "run_agent_finished.sh": "run_agent_finished.sh",
}

# Wrapper template: locates commander dir via env var with a hardcoded default,
# then calls the appropriate Python hook.
WRAPPER_TEMPLATE = """\
#!/usr/bin/env bash
# Auto-generated by scripts/provision_global_hooks.py
# Calls commander's {hook_py} from any repo's worktree.
COMMANDER_DIR="${{COMMANDER_DIR:-{commander_dir}}}"
exec "$COMMANDER_DIR/venv/bin/python3" "$COMMANDER_DIR/hooks/{hook_py}" "$@"
"""

HOOK_PY_MAP = {
    "run_tool_used.sh": "tool_used.py",
    "run_post_tool_used.sh": "post_tool_used.py",
    "run_agent_finished.sh": "agent_finished.py",
}


def build_hooks_block(global_hooks_dir: Path) -> dict:
    pre = str(global_hooks_dir / "run_tool_used.sh")
    post = str(global_hooks_dir / "run_post_tool_used.sh")
    stop = str(global_hooks_dir / "run_agent_finished.sh")
    return {
        "PreToolUse": [
            {
                "matcher": ".*",
                "hooks": [{"type": "command", "command": f"bash {pre}"}],
            }
        ],
        "PostToolUse": [
            {
                "matcher": ".*",
                "hooks": [{"type": "command", "command": f"bash {post}"}],
            }
        ],
        "Stop": [
            {
                "hooks": [{"type": "command", "command": f"bash {stop}"}]
            }
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--commander-dir",
        default=str(Path.home() / "dev/commander/prd"),
        help="Path to the commander prd clone (default: ~/dev/commander/prd)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would change without writing anything",
    )
    args = parser.parse_args()

    commander_dir = Path(args.commander_dir).expanduser().resolve()
    if not commander_dir.exists():
        print(f"ERROR: commander-dir not found: {commander_dir}", file=sys.stderr)
        print("  Pass --commander-dir <path> to specify the correct location.", file=sys.stderr)
        sys.exit(1)

    venv_python = commander_dir / "venv/bin/python3"
    if not venv_python.exists():
        print(f"ERROR: venv not found at {venv_python}", file=sys.stderr)
        print("  Create it with: python3.12 -m venv venv && venv/bin/pip install -r requirements.txt", file=sys.stderr)
        sys.exit(1)

    global_claude_dir = Path.home() / ".claude"
    global_hooks_dir = global_claude_dir / "hooks"
    global_settings = global_claude_dir / "settings.json"

    print(f"Commander dir : {commander_dir}")
    print(f"Global hooks  : {global_hooks_dir}")
    print(f"Settings file : {global_settings}")
    print()

    # --- 1. Create wrapper scripts ---
    for sh_name, py_name in HOOK_PY_MAP.items():
        hook_py_path = commander_dir / "hooks" / py_name
        if not hook_py_path.exists():
            print(f"WARNING: hook script not found: {hook_py_path} — skipping {sh_name}")
            continue

        content = WRAPPER_TEMPLATE.format(
            hook_py=py_name,
            commander_dir=str(commander_dir),
        )
        dest = global_hooks_dir / sh_name
        if args.dry_run:
            print(f"[dry-run] would write {dest}:")
            print(content)
        else:
            if dest.exists() and dest.read_text() == content:
                print(f"  unchanged {dest}")
            else:
                global_hooks_dir.mkdir(parents=True, exist_ok=True)
                dest.write_text(content)
                dest.chmod(dest.stat().st_mode | 0o111)  # make executable
                print(f"  wrote {dest}")

    # --- 2. Update ~/.claude/settings.json ---
    if global_settings.exists():
        try:
            settings = json.loads(global_settings.read_text())
        except json.JSONDecodeError as exc:
            print(f"ERROR: could not parse {global_settings}: {exc}", file=sys.stderr)
            sys.exit(1)
    else:
        settings = {}

    new_hooks = build_hooks_block(global_hooks_dir)

    existing_hooks = settings.get("hooks", {})
    changed = existing_hooks != new_hooks
    if not changed:
        print("Settings already up to date — no changes needed.")
        return

    settings["hooks"] = new_hooks

    if args.dry_run:
        print(f"\n[dry-run] would update {global_settings}:")
        print(json.dumps(settings, indent=2))
        return

    global_settings.write_text(json.dumps(settings, indent=2) + "\n")
    print(f"  updated {global_settings} with global hooks")
    print()
    print("Done. All Claude Code sessions on this machine will now report")
    print("telemetry to the Commander dashboard regardless of which repo")
    print("is active as the session cwd.")
    print()
    print("Set COMMANDER_DIR in your shell if the prd clone moves:")
    print(f"  export COMMANDER_DIR={commander_dir}")


if __name__ == "__main__":
    main()
